<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[OpenBrowser]]>
    </line>
    <line>
      <![CDATA[login]]>
    </line>
    <line>
      <![CDATA[Create Customer]]>
    </line>
    <line>
      <![CDATA[Logout]]>
    </line>
    <line>
      <![CDATA[CloseBrowser]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="23722" started-at="2023-04-12T10:03:13 IST" finished-at="2023-04-12T10:03:36 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23722" started-at="2023-04-12T10:03:13 IST" finished-at="2023-04-12T10:03:36 IST">
      <class name="com.actitime.testscript.CustomerModule">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.actitime.testscript.CustomerModule@44c8afef]" name="openBrowser" is-config="true" duration-ms="3014" started-at="2023-04-12T10:03:13 IST" finished-at="2023-04-12T10:03:16 IST">
          <reporter-output>
            <line>
              <![CDATA[OpenBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.actitime.testscript.CustomerModule@44c8afef]" name="login" is-config="true" duration-ms="7498" started-at="2023-04-12T10:03:16 IST" finished-at="2023-04-12T10:03:23 IST">
          <reporter-output>
            <line>
              <![CDATA[login]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="testCreateCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@44c8afef]" name="testCreateCustomer" duration-ms="9581" started-at="2023-04-12T10:03:23 IST" finished-at="2023-04-12T10:03:33 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HDFC_025] but found [All Customers]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HDFC_025] but found [All Customers]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.actitime.testscript.CustomerModule.testCreateCustomer(CustomerModule.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Create Customer]]>
            </line>
          </reporter-output>
        </test-method> <!-- testCreateCustomer -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.actitime.testscript.CustomerModule@44c8afef]" name="logout" is-config="true" duration-ms="2806" started-at="2023-04-12T10:03:33 IST" finished-at="2023-04-12T10:03:36 IST">
          <reporter-output>
            <line>
              <![CDATA[Logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.actitime.testscript.CustomerModule@44c8afef]" name="closeBrowser" is-config="true" duration-ms="214" started-at="2023-04-12T10:03:36 IST" finished-at="2023-04-12T10:03:36 IST">
          <reporter-output>
            <line>
              <![CDATA[CloseBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.actitime.testscript.CustomerModule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
